"""Serialise one source + its extracted passages as a MEDFORD (.mfd) file.

Core MEDFORD tags used as specified (validated by the TuftsBCB parser):
  @MEDFORD, @MEDFORD-Version, @Contributor(-Role/-Association/-Institution), @Institution,
  @Date(-Note), @Data(-Type/-URI/-Flag), @Keyword, @Freeform_Date
Oral-history extension tags (MEDFORD permits new major tags; selected values are
checked by schema/medford.yaml):
  @OralHistory-*   provenance of the interview / document
  @Passage-*       one extracted excerpt with its typed Jev decisions
  @Relation-*      a person named by the narrator + relation type (academic genealogy)
  @Extraction-*    model, thresholds, date -- so every label is traceable to a model version
"""
from __future__ import annotations

import re
from pathlib import Path

from .extract import CHOICE_ACCEPT, NOUL_ACCEPT, NOUL_REJECT, PassageRecord


def _clean(s: str) -> str:
    # MEDFORD is line-based: one value per line; '#' would start a comment, '@' a tag, '`' a macro
    s = re.sub(r"\s+", " ", s).strip()
    return s.replace("#", "No.").replace("`", "'").replace("@", "(at)")


def _date(s: str | None) -> str | None:
    # Check the expected YYYY-MM-DD shape, not whether the calendar date exists.
    return s if s and re.fullmatch(r"\d{4}-\d{2}-\d{2}", s) else None


def write_mfd(source: dict, passages: list[PassageRecord], drafty: dict | None, retrieved: str,
              model: str, out_dir: Path) -> Path:
    # Build a line-based record in memory, then save it once at the end.
    L: list[str] = []
    add = L.append
    add(f"# Oral History of Computer Science -- MEDFORD record for source '{source['id']}'")
    add("# Generated by ohcs (cs-oral-history). Excerpts are short quotations for scholarly annotation.")
    add(f"@MEDFORD Oral history record: {_clean(source['narrator'])} ({_clean(source['repository'])})")
    add("@MEDFORD-Version 2.0")
    add("")

    # affiliation stated in the source wins; Drafty is the sampling frame, not ground truth
    inst = source.get("affiliation") or (drafty["university"] if drafty else None)
    repo = source["repository"]
    # Avoid duplicate institution entries while keeping their original order.
    for i in dict.fromkeys([x for x in (inst, repo) if x]):
        add(f"@Institution {_clean(i)}")
    add("")
    add(f"@Contributor {_clean(source['narrator'])}")
    add("@Contributor-Role Narrator")
    if inst:
        add(f"@Contributor-Institution {_clean(inst)}")
        add(f"@Contributor-Association {_clean(inst)}")
    add("")
    # Memoirs have no interviewer, so this contributor block is optional.
    if source.get("interviewer"):
        add(f"@Contributor {_clean(source['interviewer'])}")
        add("@Contributor-Role Interviewer")
        add(f"@Contributor-Institution {_clean(repo)}")
        add(f"@Contributor-Association {_clean(repo)}")
        add("")

    # Record the source date separately from the date this annotation was generated.
    if _date(source.get("date")):
        add(f"@Date {source['date']}")
        add("@Date-Note Interview conducted" if source.get("interviewer") else "@Date-Note Document written")
    add(f"@Date {retrieved}")
    add("@Date-Note Retrieved and annotated")
    add("")

    # Link to the original source rather than embedding the full document.
    add(f"@Data {_clean(source['repository'])} {_clean(source.get('catalog') or '')}".rstrip())
    add("@Data-Type Website")
    add(f"@Data-URI {source['uri']}")
    add("@Data-Flag referenced")
    add("")

    add(f"@OralHistory {_clean(source['id'])}")
    add(f"@OralHistory-SourceType {source['source_type']}")
    add(f"@OralHistory-Repository {_clean(source['repository'])}")
    if source.get("catalog"):
        add(f"@OralHistory-Catalog {_clean(source['catalog'])}")
    if source.get("place"):
        add(f"@OralHistory-Place {_clean(source['place'])}")
    # Keep faculty-frame metadata and any affiliation disagreement visible for review.
    if drafty:
        add(f"@OralHistory-DraftyMatch {_clean(drafty['name'])}; {_clean(drafty['university'])}; "
            f"JoinYear {drafty['join_year']}; {_clean(drafty['subfield'])}; PhD {_clean(drafty['doctorate'])}")
        if inst and drafty["university"] != inst:
            add(f"@OralHistory-DraftyConflict Drafty lists {_clean(drafty['university'])}; source states {_clean(inst)}")
    else:
        add("@OralHistory-DraftyMatch none (not in Drafty frame)")
    add("")

    # keywords = themes accepted in >=1 passage
    kw = sorted({t for p in passages for t in p.accepted_themes})
    for k in kw:
        add(f"@Keyword theme:{k}")
    add("")

    # Save the model and thresholds so later readers can trace how labels were assigned.
    add(f"@Extraction ohcs passage coder")
    add(f"@Extraction-Model {model}")
    add(f"@Extraction-Thresholds noul_accept={NOUL_ACCEPT} noul_reject={NOUL_REJECT} choice_accept={CHOICE_ACCEPT}")
    add(f"@Extraction-Calibrated {'no (heuristic stub, not Jev)' if model.startswith('heuristic') else 'yes (Jev RLCD)'}")
    add("")

    for p in passages:
        pid = f"P{p.idx + 1}"  # Human-readable passage IDs start at P1.
        add(f"@Passage {pid}")
        add(f"@Passage-Text \"{_clean(p.text)}\"")
        if p.page:
            add(f"@Passage-Page {p.page}")
        add(f"@Passage-Years {_clean(p.years)}")
        # Writing a record does not verify its quotation against the source.
        add("@Passage-Verification pending (excerpt via web reader; verify against full text)")
        # Include accepted and reviewable themes, ordered by decreasing score.
        for code, pr in sorted(p.themes.items(), key=lambda kv: -kv[1]):
            if pr > NOUL_REJECT:
                add(f"@Passage-Theme {code} p={pr:.2f}")
        add(f"@Passage-Era {p.era} conf={p.era_conf:.2f}")
        add(f"@Passage-Function {p.function} conf={p.function_conf:.2f}")
        add(f"@Passage-Specificity {p.specificity:.0f}")
        add(f"@Passage-Affect {p.affect:.0f}")
        add(f"@Passage-Recollection p={p.is_recollection:.2f}")
        add(f"@Passage-Route {p.route}")
        add("")
        # Link each person relationship back to the passage that mentioned it.
        for r in p.relations:
            add(f"@Relation {_clean(r['person'])}")
            add(f"@Relation-Type {r['relation']} conf={r['confidence']:.2f}")
            add(f"@Relation-Passage {pid}")
            add(f"@Relation-Route {r['route']}")
            add("")

    # Use the source ID as the filename so reruns replace the same source record.
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{source['id']}.mfd"
    path.write_text("\n".join(L).rstrip() + "\n")
    return path
